CREATE DATABASE IF NOT EXISTS `jta1` DEFAULT CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS `jta2` DEFAULT CHARACTER SET utf8;
use jta1;
DROP TABLE IF EXISTS `jtatest`;
CREATE TABLE `jtatest` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

use jta2;
DROP TABLE IF EXISTS `jtatest`;
CREATE TABLE `jtatest` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;